config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:show, :edit, :update]

  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end


  get 'homes/about' => 'homes#about', as: 'about'

  devise_for :users
  root to: "homes#top"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post_image
  
  validates :user_id, uniqueness: {scope: :post_image_id}
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post_image

end

app/models/post_image.rb
class PostImage < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :shop_name, presence:true
  validates :image, presence:true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    post_images_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end
  
  def destroy
    PostComment.find(params[:id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
  
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

  def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end
  end

  def index
    @post_images = PostImage.page(params[:page])
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    post_image = PostImage.find(params[:id])
    post_image.delete
    redirect_to post_images_path
  end

# private
  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @post_images = @user.post_images.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>Aboutページ</h1>

app/views/homes/top.html.erb
<!--Colクラス、画面幅（md）で6列分、margin左右自動、上5-->
<div class="col-md-6 mx-auto mt-5">
  <h1>welcome to <strong>Meshiterro</strong>  !!</span></h1>
  <!--Bootstrapのアイコンのクラス（本）-->
  <p>In  <span class="glyphicon glyphicon-book"></span><strong>Meshiterro</strong>, </p>
  <p>SNS community that indiscriminately stimulates the appetite of sensible citizens.</p>
  <!--Rowクラス-->
  <div class="row">
    <!--margin左3--><!--ボタンのレイアウトで表示、ボタンの種類info-->
    <p class="ml-3"><a class="btn btn-info" href="/users/sign_in">Log in</a></p>
    <!--margin左3--><!--ボタンのレイアウトで表示、ボタンの種類success-->
    <p class="ml-3"><a class="btn btn-success" href="/users/sign_up">Sign Up</a></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/99724ae1be.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <!--直下の子要素をフレックスアイテムに変換、上から下に並べる、height100（ビューポート単位）-->
  <body class="d-flex flex-column vh-100">

<!--ヘッダー-->

    <!--要素自体に影を付ける（sm＝ちょっとだけ）-->
    <header class="shadow-sm">
      <!--ナビゲーションバーの使用、画面幅（lg）でナビゲーションを折り畳む、
      背景が黒系（.navbar-dark）白系（.nabvar-light）を指定（文字色などが変わる）
      v5.2.0以降、.navbar-lightは非推奨、デフォルトで"light"、.navbar-darkで上書き
      v5.3.0以降、新しいダークナビゲーションバーdata-bs-theme="dark"を使用するため、.navbar-darkを廃止-->
      <nav class="navbar navbar-expand-lg navbar-light">
        <!--コンテナクラス-->
        <div class="container">
          <!--ブランド(銘柄)を表示、padding3、クリックするとトップページに飛ぶ-->
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
          <!--ハンバーガーメニュー（ボタン）
          トグル（オンオフスイッチ）を使用
          type属性をbuttonに指定（思わぬ挙動を防ぐため）
          トグルで折り畳む（collapse）ように指定
          折り畳む対象はid="navbarNavDropdown"
          読み上げブラウザなどに付加情報として「対象、開閉状態、ラベル(文字情報)」を与える-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <!--ナビゲーションアイコン（三本線）を表示する-->
            <span class="navbar-toggler-icon"></span>
          </button>
          <!--トグルによって折り畳む内容（collapseとnavbar-collapseはセット）
          上記のボタンで折り畳む対象として指定するためにidを付与-->
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <!--トグルによって表示する内容、margin左自動-->
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <!--ナビゲーションバーのリンク、文字色ダーク-->
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿フォーム', new_post_image_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

<!--メイン-->

    <!--margin下自動-->
    <main class="mb-auto">

    <%= yield %>

    </main>

<!--フッター-->

    <!--背景色ダーク、文字色白、padding上5、下4-->
    <footer class="bg-dark text-white pt-5 pb-4">
      <!--コンテナクラス-->
      <div class="container">
        <!--Rowクラス、ガーター（左右のpadding）をなくす
        （Rowに設定されている-15pxのマイナスマージンも削除）-->
        <div class="row no-gutters">

          <!--Colクラス、画面幅（md）で横幅4列分-->
          <div class="col-md-4">
            <p>善良な市民同士で無差別に食欲を煽るSNS</p>
            <%= image_tag('logo-white.png') %>
          </div>
          <!--Colクラス、画面幅（md）で横幅8列分-->
          <div class="col-md-8">
            <!--文字色白、margin上2、下3-->
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <!--padding0、リストの先頭マーク無し-->
            <ul class="p-0 list-unstyled">
              <li>
                <!--補足情報（ツールチップ表示&音声読み上げ）追加、文字色50％白-->
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>

        </div>
      </div>
    </footer>

  </body>
</html>

app/views/post_images/_list.html.erb
<!--"card-list-container"について検索結果ゼロ、padding上下5-->
<div class="card-list-container py-5">
  <% post_images.each do |post_image| %>
  
  <!--カードのレイアウトで表示、Width50％、margin左右自動、上4、影を大きく付ける-->
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    
    <%= link_to post_image_path(post_image.id) do %>
      <!--カードの上部に画像を配置（投稿画像）-->
      <%= image_tag post_image.get_image, class: "card-img-top"; %>
    <% end %>
    
    <!--カードの中身-->
    <div class="card-body">
      <!--Rowクラス-->
      <div class="row">
        
        <!--Colクラス、横幅2列分（プロフィール画像）-->
        <div class="col-2">
          <!--margin上3、丸く表示（角を丸くする機能のサークル指定）-->
          <%= image_tag post_image.user.get_profile_image(100,100), class: "mt-3 rounded-circle"; %>
        </div>
        
        <!--Colクラス、横幅10列分（その他）-->
        <div class="col-10">
          <!--カードのタイトル-->
          <p class="card-title">
            <!--文字色ダーク-->
            <%= link_to(post_image_path(post_image.id), class: "text-dark") do %>
              <!--FontAwesomeのクラス（旗）-->
              <strong><i class="far fa-flag"></i><span> <%= post_image.shop_name %></span></strong>
            <% end %>
          </p>
          <!--カードのテキスト、本文-->
          <p class="card-text">説明：<%= post_image.caption %></p>
          <!--FontAwesomeのクラス（人）-->
          <span><i class="fas fa-user"></i> By <%= post_image.user.name %> ｜ </span>
          <!--文字色ダーク-->
          <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class: "text-dark" %></span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate post_images %>
</div>

app/views/post_images/index.html.erb
<%= render 'list', post_images: @post_images %>

app/views/post_images/new.html.erb
<!--コンテナクラス-->
<div class="container">

  <!--Rowクラス、ガーター（左右のpadding）をなくす-->
  <div class="row no-gutters">
    <!--Colクラス、横幅は画面幅（md）で5列分、画面幅（sm）で10列分、
    margin左右2、画面幅（sm）で自動、影を大きく入れる、角を丸める、
    padding左右0、上下5-->
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <!--文字色ダーク、背景色ライト、padding4、margin下0-->
      <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>
      <!--"form-body"について検索結果ゼロ、padding4-->
      <div class="form-body p-4">

        <!--アラート-->
        <% if @post_image.errors.any? %>
          <!--アラートのレイアウトで表示、
          アラートの種類はdanger（危険、色が変わるだけ）、role="alert"はセット-->
          <ul class="alert alert-danger" role="alert">
            <!--アラートの見出し-->
            <h6 class="alert-heading">
              <%= @post_image.errors.count %>件のエラーが発生しました
            </h6>
            <% @post_image.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <!--投稿欄-->
        <%= form_with model: @post_image do |f| %>
          <!--Width100％-->
          <%= f.file_field :image, accept: "image/*", class: "w-100" %>
          <!--テキスト入力のレイアウトで表示、margin下3、上4-->
          <div class="input-group mb-3 mt-4">
            <!--テキスト入力に付記する（前）
            v4では記載が必要、v5では記載が不要-->
            <div class="input-group-prepend">
              <!--付記するテキスト、音声読み上げスキップ--><!--FontAwesomeのクラス（建物）-->
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <!--入力欄、入力前に薄く「ショップ名」と表示する-->
            <%= f.text_field :shop_name, class: "form-control", placeholder: "ショップ名" %>
          </div>
          <!--入力欄、高さは3行分、入力前に薄く「コメントここに」と表示する-->
          <%= f.text_area :caption, class: "form-control", rows: "3", placeholder: "コメントここに" %>
          
          <hr> <!--横線-->
          
          <!--ボタンのレイアウトで表示、大きさは大、親要素の幅に合わせる、
          ボタンの種類はinfo（情報、色が変わるだけ）、margin上4
          ボタンの幅を親要素に合わせる場合、btn-blockを使うのはv4
          v5ではdisplayユーティリティとgapユーティリティを組み合わせる-->
          <%= f.submit '投稿', class: "btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<!--"post-detail"について検索結果ゼロ、padding上下5、背景色ライト-->
<div class="post-detail py-5 bg-light">

  <!--カードのレイアウトで表示、Width75％、margin左右自動、上4、影を大きく付ける-->
  <div class="card w-75 mx-auto mt-4 shadow-lg">

    <!--カードの上部に画像を配置（投稿画像）-->
    <%= image_tag @post_image.get_image, class:"card-img-top"; %>

    <!--カードの中身-->
    <div class="card-body">
      <!--Rowクラス-->
      <div class="row">
        <!--Colクラス、横幅2列分（プロフィール画像）-->
        <div class="col-2">
          <!--margin上3、丸く表示（角を丸くする機能のサークル指定）-->
          <%= image_tag @post_image.user.get_profile_image(100,100), class:"mt-3 rounded-circle";  %>
        </div>

        <!--Colクラス、横幅10列分（その他）-->
        <div class="col-10">

          <!--カードのタイトル-->
          <p class="card-title">
            <!--文字色ダーク-->
            <%= link_to(post_image_path(@post_image.id), class:"text-dark") do %>
              <!--FontAwesomeのクラス（旗）-->
              <strong><i class="far fa-flag"></i><span> <%= @post_image.shop_name %></span></strong>
            <% end %>
          </p>

          <!--カードのタイトル、本文-->
          <p class="card-title">説明：<%= @post_image.caption %></p>
          <!--FontAwesomeのクラス（人）-->
          <span><i class="fas fa-user"></i> By <%= @post_image.user.name %> ｜ </span>
          <!--FontAwesomeのクラス（カレンダー）-->
          <span><i class="fa fa-calendar"></i> <%= @post_image.created_at.strftime('%Y/%m/%d') %> ｜ </span>
          <span>
            <!--FontAwesomeのクラス（ふきだし）-->
            <i class="fa fa-comment"></i>
            <!--文字色ダーク-->
            <%= link_to "#{@post_image.post_comments.count}", post_image_path(@post_image.id), class:"text-dark" %> ｜
          </span>

          <!--いいね機能-->
          <% if @post_image.favorited_by?(current_user) %>
            <span>
              <!--文字色ダーク-->
              <%= link_to(post_image_favorite_path(@post_image), class:"text-dark", method: :delete) do %>
                <!--FontAwesomeのクラス（ハート）、音声読み上げスキップ-->
                <i class="fa fa-heart" aria-hidden="true"></i> <%= @post_image.favorites.count %>
              <% end %>
            </span>

            <% else %>
            <span>
              <!--文字色ダーク-->
              <%= link_to(post_image_favorite_path(@post_image), class:"text-dark", method: :post) do %>
                <!--FontAwesomeのクラス（ハート）、音声読み上げスキップ-->
                <i class="fa fa-heart" aria-hidden="true"></i> <%= @post_image.favorites.count %>
              <% end %>
            </span>
          <% end %>

          <!--記事削除機能-->
          <% if @post_image.user == current_user %>
            <!--文字色ダーク-->
            <span> ｜ </span><%= link_to "削除", post_image_path(@post_image), class:"text-dark", method: :delete %>
          <% end %>

        </div>

      </div>

      <hr> <!--区切り線-->

      <!--コメント機能-->
      <!--"comments"について検索結果ゼロ、カードのテキスト、本文-->
      <div class="comments card-text">
        <!--margin上3-->
        <h4 class="mt-3"><%= @post_image.post_comments.count %>件コメント</h4>

        <% @post_image.post_comments.each do |post_comment| %>
          <!--メディアのレイアウトで表示、枠線表示、margin下3-->
          <div class="media border mb-3">
            <!--"bd-placeholder-img"について検索結果は出るが適切な情報を見つけられず、縦位置中央揃え、margin左右3-->
            <%= image_tag post_comment.user.get_profile_image(60,60), class:"bd-placeholder-img align-self-center mx-3";  %>
            <!--メディアの中身、margin左4、padding3-->
            <div class="media-body ml-4 p-3">
              <p><%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %></p>
              <p><%= post_comment.comment %></p>

              <% if post_comment.user == current_user %>
                <!--ボタンのレイアウトで表示、ボタンの種類はdanger、右寄せ
                右寄せを"pull-right"で行うのはv3、v4以降は削除されており使えない-->
                <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete, class: "btn btn-danger pull-right" %>
              <% end %>

            </div>
          </div>
        <% end %>

      </div>

      <hr> <!--区切り線-->

      <!--"new-comment"について検索結果ゼロ、カードのテキスト、本文-->
      <div class="new-comment card-text">
        <%= form_with(model:[@post_image, @post_comment]) do |f| %>
          <!--入力欄を囲う部分の設定-->
          <div class="form-group">
            <!--forでidを指定（なぜかフォーム側にidがない？）-->
            <label for="exampleFormControlTextarea1">コメントする</label>
            <!--高さは5行分、入力欄、入力前に薄く「コメントをここに」と表示する-->
            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
          </div>
          <!--ボタンのレイアウトで表示、大きさは大、ボタンの種類はinfo、margin上2、右寄せ
          右寄せを"pull-right"で行うのはv3、v4以降は削除されており使えない
          が、なぜか右寄せできてる？-->
          <%= f.submit "送信する", class:"btn btn-lg btn-info mt-2 float-right" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/users/edit.html.erb
<!--コンテナクラス-->
<div class="container">

  <!--Rowクラス、ガーター（左右padding）なし-->
  <div class="row no-gutters">

    <!--Colクラス、画面幅（md）で横幅5列分、（sm）で10列分、margin左右2、画面幅（sm）で自動、
    テキスト位置中央揃え、影を大きく付ける、角を丸める、padding左右0、上下5-->
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
      <!--文字色ダーク、背景色ライト、padding上下4、margin下0-->
      <h5 class="text-dark bg-light py-4 mb-0">プロフィール編集</h5>
      <!--"form-body"について検索結果ゼロ、padding4-->
      <div class="form-body p-4">

        <%= form_with model: @user, local: true do |f| %>
          <!--テキスト入力のレイアウトで表示、margin下3-->
          <div class="input-group mb-3">
            <!--テキスト入力に付記する（前）
            v4では記載が必要、v5では記載が不要-->
            <div class="input-group-prepend">
              <!--付記するテキスト、音声読み上げスキップ--><!--FontAwesomeのクラス（人）-->
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-user"></i></span>
            </div>
            <!--自動で入力状態になる、入力欄、idを付与（なぜ？）、入力前に薄く「名前」と表示する-->
            <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputName", placeholder:"名前"%>
          </div>

          <!--入力欄、margin上下3-->
          <div class="input-group my-3">
            <!--テキスト入力に付記する（前）
            v4では記載が必要、v5では記載が不要-->
            <div class="input-group-prepend">
              <!--付記するテキスト、音声読み上げスキップ--><!--FontAwesomeのクラス（写真）-->
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-image"></i></span>
            </div>
            <!--ファイル（データ）をアップロードするフォームを囲む-->
            <div class="custom-file">
              <!--ファイル（データ）をアップロードするフォーム、画像データだけ、見えなくする-->
              <%= f.file_field :profile_image, class: 'custom-file-input', accept: "image/*", style: "display: none;" %>
              <!--ファイル（データ）をアップロードするフォームのラベル、forでidを指定する（idがない？）、テキスト位置左-->
              <label class="custom-file-label" for="user_profile_image" style="text-align: left;">プロフィール画像</label>
            </div>
          </div>

          <!--ボタンのレイアウトで表示、大きさは大、幅を親要素に揃える、種類はinfo、margin上5
          ボタンの幅を親要素に合わせる場合、btn-blockを使うのはv4
          v5ではdisplayユーティリティとgapユーティリティを組み合わせる-->
          <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-info mt-5" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- ユーザーの詳細 -->

<!--"profile-container"は検索結果ゼロ、width75％、子要素をフレックスボックスにする、margin左右自動
左右位置均等割り付け、縦位置は中央揃え、下の枠線を表示、padding上下5-->
<div class="profile-container w-75 d-flex mx-auto justify-content-around align-items-center border-bottom py-5">
  <!--丸く表示する-->
  <%= image_tag @user.get_profile_image(100,100), class:"rounded-circle";  %>
  <!--"profile-name"は検索結果ゼロ、見出しの大きさ4（大1～6小）-->
  <h5 class="profile-name display-4"><%= @user.name %></h5>
  <% if @user.id == current_user.id %>
    <!--margin上自動-->
    <div class="mt-auto">
    <!--文字色ダーク-->
      <p><%= link_to "プロフィール編集", edit_user_path(@user), class:"text-dark" %></p>
    </div>
  <% end %>
</div>

<!-- ユーザーの投稿一覧 -->
<%= render 'post_images/list', post_images: @post_images %>